[tool.poetry]
name = "ai_assistant"
version = "0.0.3"
authors = [
    "Anand <anand1911991@outlook.com>",
]
description = "Template repo for building GenAI applications"
readme = "README.md"
repository = "https://github.com/Anand191/one-click-rag.git"
packages = [
    {include = "ai_assistant"}
]
exclude = ["tests*"]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
# Basic Libs
pyyaml = "^6.0.2"
pandas = "^2.2.3"
pandera = "^0.23.1"
loguru = "^0.7.3"
pydantic = "^2.11.2"
pydantic-settings = "^2.8.1"
python-dotenv = "^1.1.0"
openpyxl = "^3.1.5" # used by the logging library
tqdm = "^4.67.1"
# DL Related
torch = "^2.6.0"
sentence-transformers = "^2.4.0"
transformers = "^4.51.2"
accelerate = "^1.6.0"
datasets = "^3.5.0"
lightning = "^2.5.1"
torchmetrics = "^1.7.1"
# LLM Related
chromadb = "^1.0.4"
openai = "^1.73.0"
dspy-ai = "^2.6.17"
langchain = "^0.3.23"
langchain-core = "^0.3.51"
langchain-openai = "^0.3.12"
langchain-google-vertexai = "^2.0.20"
langchain-community = "^0.3.21"
# API Related
redis = "^5.2.1"
fastapi = "^0.115.9"
uvicorn = "^0.34.0"
typer = "^0.12.5"
# Azure related
azure-identity = "^1.21.0"
azure-keyvault = "^4.2.0"
azure-search-documents = "^11.5.2"
azure-storage-blob = "^12.25.1"
azure-functions = "^1.23.0"
# GCP Related
opentelemetry-exporter-otlp-proto-grpc = "1.32.0"
google-auth = "^2.38.0"
google-cloud-discoveryengine = "^0.13.8"
googleapis-common-protos = "^1.69.2"
google-api-python-client = "^2.166.0"
google-auth-httplib2 = "^0.2.0"
google-auth-oauthlib = "^1.2.1"
google-cloud-storage = "^2.19.0"
google-cloud-aiplatform = "^1.88.0"
google-cloud-documentai = "^3.3.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-watch = "^4.2.0"
pytest-cov = "^6.1.1"
pytest-xdist = "^3.6.1"
pytest-mock = "^3.14.0"
joblib = "^1.4.2"
ruff = "^0.8.6"
pylint = "^3.3.6"
black = "^25.1.0"
isort = "^6.0.1"
flake8 = "^7.2.0"
deptry = "^0.23.0"

[tool.poetry.group.experimentation]
optional = true

[tool.poetry.group.experimentation.dependencies]
jupyterlab = "^4.4.0"
ipywidgets = "^8.1.6"
ragas = "^0.2.14"
pypdf2 = "^3.0.1"
unstructured = {extras = ["md", "pdf"], version = "^0.17.2"}
docling-core = "^2.26.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --strict-markers -m 'not integration and not redis'"
markers = [
    "integration: mark test as integration test" ,
    "redis: mark test as redis based"
]

[tool.deptry]
ignore = ["DEP004"]
ignore_notebooks = true
extend_exclude = ["src"]

[tool.deptry.per_rule_ignores]
DEP002 = ["openpyxl"]

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "models",
    "data",
    "notebooks",
    "logs",
    "assets",
    # this is only temporary
    "src"
]

line-length = 110
indent-width = 4
target-version = "py311"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]
ignore = ["E731"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
